version: '3'

services:
  api:
    container_name: api
    build:
      context: .
    volumes:
      - .:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - ./pg-container/pg_init.sh:/docker-entrypoint-initdb.d/pg_init.sh
    ports:
      - "5432:5432"
    expose:
      - "5432"